### ISSUE TITLE
"Creative world map" image in Readme

### ISSUE THREAD

**Issue by ElOceanografo** [joa-quim/GMT.jl#1]
I don't think the Jessica Rabbit image in the Readme is really appropriate--it crosses the line into "sexual imagery" and could make a lot of people uncomfortable, see e.g. the [Julia Community Standards](http://julialang.org/community/standards/).  I'd suggest replacing it with something else.  Maybe [Grumpy Cat](http://ppcorn.com/us/wp-content/uploads/sites/14/2015/07/grumpy_cat_ppcore.jpg)?

**Comment by joa-quim** [comment]
Excuse but I'm going to close this. Saying that using a Jessica Rabit image can make  lots of people uncomfortable is a clear exaggeration to me.
