### ISSUE TITLE
install GMT 5 beside GMT 4.5

### ISSUE THREAD

**Issue by alirezaniki** [joa-quim/GMT.jl#4]
HI every body 
How can i install GMT 5 beside preinstalled GMT4 and work with both of them?
is this possible?

**Comment by joa-quim** [comment]
Yes, it is but the solution depends on the OS. See [this ](http://gmt.soest.hawaii.edu/doc/5.3.2/GMT_Docs.html#switching-between-different-gmt-versions) in GMT docs

**Comment by alirezaniki** [comment]
Many thanks Dear Joa
